name: Build

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Resolve Swift Deendencies
        run: swift package resolve
      
      - name: Build Vapor App
        run: swift build -c release --static-swift-stdlib

       

      
