name: Build

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Resolve Swift Deendencies
        run: swift package resolve
      
      
      
