name: Build

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Chache Swift build directory
        uses: actions/cache@v3
        with: 
          path: .build
          key: ${{ runner.os }}-swift
      
      - name: Resolve Swift Deendencies
        run: swift package resolve
      
      - name: Build Vapor App
        run: swift build -c release --static-swift-stdlib

      - name: Create staging directory
        run: |
          mkdir staging
          cp "$(swift build -c release --show-bin-path)/Run" ./staging
          find -L "$(swift build -c release --show-bin-path)/" -regex '.*\.resources$' -exec cp -Ra {} ./staging/ \;
          [ -d ./Public ] && { mv ./Public ./staging/Public && chmod -R a-w ./staging/Public; } || true
          [ -d ./Resources ] && { mv ./Resources ./staging/Resources && chmod -R a-w ./staging/Resources; } || true
          echo "```$(ls -la)```" >> $GITHUB_STEP_SUMMARY


       

      
